### ISSUE TITLE
Test failure (test build failure)

### ISSUE THREAD

**Issue by mihaimaruseac** [google/proto-lens#119]
In stackage nightly. Full trace:

```
> /tmp/stackage-build14/proto-lens-combinators-0.1.0.8$ ghc -clear-package-db -global-package-db -package-db=/var/stackage/work/builds/nightly/pkgdb -hide-all-packages -package=Cabal -package=base -package=proto-lens-protoc Setup
[1 of 1] Compiling Main             ( Setup.hs, Setup.o )
Linking Setup ...
> /tmp/stackage-build14/proto-lens-combinators-0.1.0.8$ ./Setup configure --enable-tests --package-db=clear --package-db=global --package-db=/var/stackage/work/builds/nightly/pkgdb --libdir=/var/stackage/work/builds/nightly/lib --bindir=/var/stackage/work/builds/nightly/bin --datadir=/var/stackage/work/builds/nightly/share --libexecdir=/var/stackage/work/builds/nightly/libexec --sysconfdir=/var/stackage/work/builds/nightly/etc --docdir=/var/stackage/work/builds/nightly/doc/proto-lens-combinators-0.1.0.8 --htmldir=/var/stackage/work/builds/nightly/doc/proto-lens-combinators-0.1.0.8 --haddockdir=/var/stackage/work/builds/nightly/doc/proto-lens-combinators-0.1.0.8 --flags=
Configuring proto-lens-combinators-0.1.0.8...
> /tmp/stackage-build14/proto-lens-combinators-0.1.0.8$ ghc -clear-package-db -global-package-db -package-db=/var/stackage/work/builds/nightly/pkgdb -hide-all-packages -package=Cabal -package=base -package=proto-lens-protoc Setup
> /tmp/stackage-build14/proto-lens-combinators-0.1.0.8$ ./Setup build
unrecognized option `--plugin=protoc-gen-haskell=/var/stackage/work/builds/nightly/bin/proto-lens-protoc'
unrecognized option `--haskell_out=dist/build/global-autogen'
unrecognized option `--proto_path=tests'
Usage: protoc [OPTION]... FILES
  -h  --help     show usage
  -v  --version  show version number

Preprocessing library for proto-lens-combinators-0.1.0.8..
Building library for proto-lens-combinators-0.1.0.8..
[1 of 1] Compiling Data.ProtoLens.Combinators ( src/Data/ProtoLens/Combinators.hs, dist/build/Data/ProtoLens/Combinators.o )
Preprocessing test suite 'combinators_test' for proto-lens-combinators-0.1.0.8..
Setup: can't find source for Proto/Combinators in tests,
dist/build/combinators_test/autogen, dist/build/global-autogen
```

**Comment by judah** [comment]
Thanks for the report.  From what I can tell, this is a conflict with the `protobuf-simple` package.  

Specifically: `proto-lens-*` packages assume that Google's official `protoc` binary is on the PATH, and we do install it for the stack build:
https://github.com/fpco/stackage/blob/master/debian-bootstrap.sh#L198

But `protobuf-simple` also creates its own `protoc` binary, which gets installed on the path and shadows the preinstalled binary:
https://github.com/sru-systems/protobuf-simple/blob/master/protobuf-simple.cabal#L78

I'm not sure what changed since the last LTS, where everything appeared to be working correctly (and, if I'm understanding right, both `proto-lens-protoc` and `protobuf-simple` were present).

What is the exact `$PATH` for the stackage build machine?

@mrijkeboer, any suggestions how to work around this?  Is there a way to avoid installing `protobuf-simple`'s `protoc`, or would it break tests in that package?

**Comment by blackgnezdo** [comment]
Alternatively, can we avoid using a global resource like PATH? Is there a package-private location where everything can be launched from? We could rename protoc to something very unlikely to collide with anything else but it's a hack rather than a solution.

**Comment by mrijkeboer** [comment]
@judah: `protobuf-simple` doesn't use `protoc` for its tests, however, I don't see a nice way to avoid installing `protobuf-simple`'s `protoc`. I do think that @blackgnezdo idea of avoiding a global resource like PATH is the way to go (if possible), because sooner or later there will be another package that ships a `protoc` binary.

I'm also curious what has changed since the last LTS since both `protobuf-simple` and `proto-lens-protoc` are present in [LTS-9.0](https://www.stackage.org/lts-9.0).
