### ISSUE TITLE
lenses 101

### ISSUE THREAD

**Issue by awalterschulze** [google/proto-lens#230]
This is my first time using lenses, so hopefully this is a really stupid question.

I see that this code, which does not use lenses works:

```haskell
import qualified Proto.Google.Protobuf.Descriptor as D

couldBePacked :: D.FieldDescriptorProto -> Bool
couldBePacked field = ( D._FieldDescriptorProto'label field  ) == (Just D.FieldDescriptorProto'LABEL_REPEATED)
```

But this code does not

```haskell
import Lens.Micro ((^.))
import qualified Proto.Google.Protobuf.Descriptor as D

couldBePacked2 :: D.FieldDescriptorProto -> Bool
couldBePacked2 field = ( field .^ D.maybe'label ) == (Just D.FieldDescriptorProto'LABEL_REPEATED)
```

It gives the following error

```
Not in scope: ‘D.maybe'label’
Module ‘Proto.Google.Protobuf.Descriptor’ does not export ‘maybe'label’.
```

I also tried the `^?` operator, but I get the same error.

May I ask what I am doing wrong?

**Comment by judah** [comment]
Thanks for the question.  The lens `maybe'label` is not exposed from the module `Proto.Google.Protobuf.Descriptor`, but instead from the associated module `Proto.Google.Protobuf.Descriptor_Fields`.  We organize the generated code this way because the lens is *overloaded* and may be used with any message type that has a field of the same name.

Check out the tutorial for more information: https://github.com/google/proto-lens/tree/master/proto-lens-tutorial/person#message-and-lenses

**Comment by awalterschulze** [comment]
Ah thanks, that works :)

I was looking at the tutorial, but my skimming of the tutorial didn't reveal how to access fields.
Then I found the other tutorial https://github.com/google/proto-lens/blob/master/docs/tutorial.md and started puzzling from `accessBaz` example and then I saw further down

```haskell
import Microlens           ((^.))
import Proto.Foo        as P
import Proto.Foo_Fields as P

myBar :: P.Bar
myBar = defMessage
            & P.baz   .~ 42
            & P.bippy .~ "querty"

main :: IO ()
main = putStrLn $ myBar ^. P.bippy
```

but I missed the import of Foo_Fields

Thanks again for your help
