### ISSUE TITLE
Release for ghc-8.6.1

### ISSUE THREAD

**Issue by mpickering** [google/proto-lens#236]
This issue is to track progress towards releasing a version of `proto-lens` which is compatible with `ghc-8.6.1` which will be released in the next few days.

**Comment by judah** [comment]
I just tried a quick hack to the repo's `stack.yaml` to see where the build currently fails:

https://gist.github.com/judah/02672a86ba65852e5a57fbefd65767bb

Some packages (both dependencies and proto-lens-*) need bounds to be bumped, which I assume will happen after the actual release of 8.6.1.  Notably, `polyparse` which is used transitively by `haskell-src-exts` also needs an update due to how MonadFail works.

Log: https://gist.github.com/judah/02672a86ba65852e5a57fbefd65767bb

**Comment by mpickering** [comment]
`haskell-src-exts` is my responsibility but like you say, I can't do a release until `polyparse` is updated.

**Comment by mpickering** [comment]
I just released `haskell-src-exts-1.20.3` which is compatible with `ghc-8.6.1`.

**Comment by judah** [comment]
Update: I've created a branch (`ghc-8.6`) for this task, which mostly works: https://github.com/google/proto-lens/compare/ghc-8.6?expand=1

However, this requires using some dependencies that aren't released yet (e.g. tagged, contravariant), and a couple local packages still aren't built (`proto-lens-benchmarks` and `proto-lens-discrimination`) due to dependencies that haven't been upgraded yet.

At this point I'm planning to wait another couple weeks for the dependencies to get updated and released.

**Comment by mpickering** [comment]
Thanks Judah. That will be enough for me to get started.

**Comment by judah** [comment]
I've released proto-lens-0.4.0.1 (and related versions of the other packages) which are all compatible with ghc-8.6.1.
