### ISSUE TITLE
Where to add a Plated DescriptorProto instance?

### ISSUE THREAD

**Issue by lucasdicioccio** [google/proto-lens#266]
Hi, for some tool I'm preparing I had to define:

```haskell
instance Plated DescriptorProto where
  plate = nestedType . traversed
```

so that it's possible to recursively traverse all DescriptorProtos from a FileDescriptorSet with
`fds ^.. file . traversed . messageType . traversed . cosmos`
.

I would be more than happy to upstream that 3-lines patch but since `~/code/proto-lens/proto-lens/src/Proto/Google/Protobuf/Descriptor.hs` has the "This file was auto-generated" header I'm unsure whether it's the best place to put that.

You don't need to wait for a PR and can go away with patching directly (I signed the CLA and already contributed a patch to proto-lens as a Xoogler).

**Comment by judah** [comment]
Thank you for the suggestion.  So far we've avoided having a dependency on the full `lens` package (which provides the `Plated` class), and I'm a little wary of adding it.

You're also right that there's no obvious place to put this instance without either having an orphan instance, or autogenerating it for all proto types (which seems tricky, especially since protos aren't instances of Data ; see #167).

In this particular case, would it have been enough to replace `cosmos` with `cosmosOf nestedType`?

**Comment by lucasdicioccio** [comment]
Thanks for the answer Judah. I had not realised that `lens` itself was not already a dependency. I understand the design point. I'll do with `cosmosOf nestedType` or orphan instances for my simple need. I didn't mean to generate Plated for all protos as I only had a need for DescriptorProto recently.

That said, discovering immediately-nested recursion of generated types in proto-lens-protoc (rather than asking GHC to do so with Generics/Data) seems doable.
