### ISSUE TITLE
Message fields are not exported anymore

### ISSUE THREAD

**Issue by vrom911** [google/proto-lens#314]
In the latest version I noticed that `proto-lens` stops exporting constructors and fields of the Messages. This change is very unexpected and I even wonder if that could be unintended behaviour as there are even no mentions of it in the CHANGELOG.

Could you please bring back this functionality so we can bump to the newer version safely?

Thanks in advance.

**Comment by judah** [comment]
That change was made intentionally for proto-lens-protoc-0.4.0.0, as listed in the changelog for proto-lens-protoc here:
http://hackage.haskell.org/package/proto-lens-protoc-0.4.0.0/changelog
It accompanied the major version bump from 0.3.* to 0.4.*.

W put together a migration guide listing all the changes from 0.3.* to 0.4.*:
https://github.com/google/proto-lens/wiki/Migration-Guide

I appreciate that API churn may cause additional work for users of the library.  This decision was not made lightly, and was based on experience using proto-lens in anger.
The PR for that specific change is here, and contains some motivation:
https://github.com/google/proto-lens/pull/174

Perhaps it would be more useful if we kept a single "master" changelist that covered both proto-lens and proto-lens-protoc (and a couple other related packages)?  I could take another look into how to organize that.

**Comment by vrom911** [comment]
@judah thanks for your reply! I surely missed this note in the CHANGELOG for the earliest version in the `proto-lens-protoc`, thanks for the links.

However, using `defMessage` instead of raw constructors is an unsafe way of building messages in big applications. Since generated data types have strict fields, we have the compiler error in case the structure of the message is changed, and anybody forgets to update it on the use site.

Besides, importing constructors and fields doesn't harm. One who is against this practice could always use `defMessages`, but the inability of constructing the messages in a safe way is a stopper for using this library in production applications. Moreover, it is much easier to detect when somebody using the fields in the project that restricts using them than to chase all usages of the `defMessages` and update them correspondingly each time and not to miss anything.

Is it possible to return the reexporting the constructors and their fields? I like how the project is improving in the newest versions so I would love to continue using the most recent one, however without this feature we would need to either maintain our own fork or use something different.
The solution of using the old version doesn't suit for us as we are moving to the GHC 8.6 and it is not compatible with the latest stack resolver.

**Comment by judah** [comment]
I understand that migrating to the new api may cause significant code churn.  I've released new versions of the packages on the proto-lens-0.3.* line that are compatible with GHC 8.6 and Stack lts-13.  Looking back, ghc-8.6.1 and proto-lens-0.4.0.0 were released in the same month so it seems reasonable to backport the fixes, which were pretty minor.  You can find the full list of new versions in:

889889d1b5d17f68f0a5e507358aa0f56394bba7

With respect to your concerns about application structure and type safety: protocol buffers were fundamentally designed so that the spec in the `.proto` file can change without applications noticing.  For example, they may ignore fields they received but didn't recognize, or fill in defaults for fields they expected but didn't receive.  I do agree that this feature is in conflict with the type safety that we are used to from Haskell and other strictly-typed languages --- but I think this tension is inherent to any evolving data schema.

Instead, I recommend separating your types into two sets: "domain" types that are used in the majority of your application's logic and have strict constructors, and "proto" types that are used only at the edge of your application for (de)serialization purposes.  I've seen this design pattern used effectively on a variety of teams, using several programming languages including Haskell, C++, etc.

A good analogy might be JSON and the `aeson` package:
- A serialized JSON object corresponds to aeson's [Value](http://hackage.haskell.org/package/aeson-1.4.2.0/docs/Data-Aeson.html#t:Value) type
- You write functions (or have boilerplate generated for you) to convert the `Value` to/from a Haskell value
- Your main domain logic operates on those Haskell domain types

In my opinion, the raw `Value` is the best analogy for the proto types, rather than the Haskell domain types.  

It's unfortunate that this approach does require more boilerplate.  I've been turning over in my head whether we could abstract some of that out to be reusable, perhaps using Generic like aeson, TemplateHaskell, or some other type-level magic.  But I haven't come up with a reasonable design yet.

**Comment by blackgnezdo** [comment]
@vrom911, every library makes some things easy at the expense of making other things hard. The purpose of proto-lens is to make working with protocol buffer data easy. Protocol buffers made a number of sacrifices to support evolving data. Towards that end there's no such thing as required fields in proto3 specification. For Haskell code this means we start with the notion of `defMessage`. So, yes, we sacrifice the ability to enforce Haskell level invariants to be align with protocol buffers goals.

One way to provide better validity guarantees is to introduce smart constructors and prohibit `defMessages` usage outside of them.

I appreciate the pain of upgrading over this API change. I had to chase down the usages of constructors in Haskell code base at Google. It wasn't fun.

**Comment by vrom911** [comment]
@judah @blackgnezdo Thank you very much for your explanations!

We do understand the area where to use `proto` types, so we do use them only at the edge zone. All my concerns are primarily about actions in that edge zone.

I see that my request is not fitting in the plans for this package, so I'm closing the issue.
Thanks again for your reasoning and discussion.
