### ISSUE TITLE
Please use vectors instead of lists for packed values

### ISSUE THREAD

**Issue by danielwaterworth** [google/proto-lens#58]
This library is a memory hog when it comes to parsing repeated packed scalar types. It would be nice if it would use contiguous arrays instead of lazy lists where appropriate.

**Comment by judah** [comment]
It may be better to just always store POD types as contiguous arrays, regardless of whether the field has the "packed" attribute.  In particular, that attribute is supposed to be both backwards- and forwards- compatible:
https://developers.google.com/protocol-buffers/docs/encoding#packed
In other words, it's problematic if a backwards-compatible change to the .proto file causes user code to break (by changing the type of the Haskell record field).

A related idea is for our codegen to create both the lenses `foo :: Lens' Foo [a]` and `foo'packed :: Lens' Foo (Unboxed.Vector a)` (for example).  Not sure whether that's worth the extra complexity vs just always providing `foo :: Lens' Foo (Unboxed.Vector a)`.

**Comment by danielwaterworth** [comment]
I started implementing this and came to the same conclusion; that repeated fields should always be vectors. I have something that works, but it's still using lots of memory. I suspect I need to make things more strict. Is there a good reason not to turn on the StrictData pragma in all generated files?

**Comment by judah** [comment]
It's tricky because of nested message.  Consider the following types:

    data Foo = Foo { a :: Maybe Int }
    data Bar = Bar { b :: [Foo] }

Even if you use `StrictData`, those types will be effectively lazy since `[]` and `Maybe` are lazy.

Possibly we could work around this by making the generated lens accessors force the fields, but I'm not sure that would be efficient in all use cases (for example: nested repeated messages).

Also keep in mind that the actual encoding/decoding code mainly focuses on correctness and has not been seriously optimized yet; some of your poor memory usage may be coming from that.  

Would you be able to post example code that exhibits the bad memory behavior?  Maybe see whether code that just encodes or decodes a specific message (or messages) exhibits the same behavior?

Side note: we still want to support 7.10.3 which doesn't have `-XStrictData`.  You could accomplish the same thing by annotating the field types `!` (I believe in haskell-src-exts: with `TyBang BangedTy`).

**Comment by judah** [comment]
Another option, depending on how you're using the library, is to try forcing the proto data structs via `deepseq`.  Currently you need to derive the `NFData` class manually; see for example:
https://github.com/google/proto-lens/blob/master/proto-lens-benchmarks/benchmarks/Nested.hs#L24

It may be reasonable to make our generated code always derive Generic and/or NFData (not sure how much code bloat that would cause).

**Comment by danielwaterworth** [comment]
It would be useful to derive Generic anyway. I working on this today. I'll make a test case and see how far I get.

**Comment by judah** [comment]
Update: after #63, which fixed several space leaks, the performance on memory_test from #60 is significantly improved in both space usage and raw time (though still nowhere near as good as if we used 'Vector' instead of lists).

For reference: on my laptop, that test now takes about 3.5 minutes and (estimating from `top`) around 3-4GB for a proto containing 100M floats (or 400MB of actual data).
